Upgrade jcoulds and gson
Upgrade of guava created an incompatibility with some usage of it inside jclouds (NoSuchMethodError).

Upgrading jclouds should remove this incompatibility (though it may create other issues)